"""
This script generates an OpenTOPAS macro that replaces a broad beam
with many pencil beams distributed uniformly on a square grid inside
an elliptical aperture. The total number of primary histories equals
the broad beam's total to preserve overall flux.
"""

from math import ceil
import numpy as np
from pathlib import Path

from matplotlib import pyplot as plt
import seaborn as sns

# ---------------------- CONFIG ----------------------
# Beam source
TOTAL_HISTORIES = 1_000_000
ENERGY_MEV = 6.0
PARTICLE = "gamma"

# Beam geometry
RX_MM = 25.0
RY_MM = 25.0
TRANSZ_MM = 0.0

SPACING_MM = 2.0                    # center-to-center spacing of pencil beams
PENCIL_HAS_SPREAD = False           # set True for finite mini-spots
PENCIL_SPREAD_MM = 0.5              # only used if PENCIL_HAS_SPREAD=True

out_path = Path("pencil_beams.txt")

# Build grid covering the ellipse bounding box
xs = np.arange(-RX_MM, RX_MM + 1e-6, SPACING_MM)
ys = np.arange(-RY_MM, RY_MM + 1e-6, SPACING_MM)
xx, yy = np.meshgrid(xs, ys)
mask = (xx / RX_MM) ** 2 + (yy / RY_MM) ** 2 <= 1.0

positions = np.column_stack([xx[mask], yy[mask]])
n_beams = positions.shape[0]

# Distribute histories as evenly as possible
base = TOTAL_HISTORIES // n_beams
rem = TOTAL_HISTORIES % n_beams
histories = np.full(n_beams, base, dtype=int)
# Give one extra history to the first 'rem' beams to match the exact total
if rem > 0:
    histories[:rem] += 1

# Compose macro text
lines = []
lines.append("# Autogenerated macro: pencil beam tiling matching broad beam flux")
lines.append("# Parameters:")
lines.append(f"#   total_histories = {TOTAL_HISTORIES}")
lines.append(f"#   energy = {ENERGY_MEV} MeV, particle = {PARTICLE}")
lines.append(f"#   ellipse Rx,Ry = {RX_MM} mm, {RY_MM} mm")
lines.append(f"#   spacing = {SPACING_MM} mm, n_beams = {n_beams}")
lines.append("")


for idx, ((x_mm, y_mm), nh) in enumerate(zip(positions, histories), start=1):
    comp = f"BeamPos{idx}"
    src  = f"Beam{idx}"
    # Geometry: place a group where this pencil beam will emit from
    lines += [
        f's:Ge/{comp}/Parent = "World"',
        's:Ge/{}/Type   = "Group"'.format(comp),
        'd:Ge/{}/TransX = {:.3f} mm'.format(comp, x_mm),
        'd:Ge/{}/TransY = {:.3f} mm'.format(comp, y_mm),
        'd:Ge/{}/TransZ = {:.3f} mm'.format(comp, TRANSZ_MM),
        ""
    ]
    # Source: pencil beam at that component
    lines += [
        f's:So/{src}/Type        = "Beam"',
        f's:So/{src}/Component   = "{comp}"',
        f's:So/{src}/BeamParticle = "{PARTICLE}"',
        f'd:So/{src}/BeamEnergy   = {ENERGY_MEV:.3f} MeV',
    ]
    if PENCIL_HAS_SPREAD:
        lines += [
            f's:So/{src}/BeamPositionDistribution = "Flat"',
            f'd:So/{src}/BeamPositionSpreadX      = {PENCIL_SPREAD_MM:.3f} mm',
            f'd:So/{src}/BeamPositionSpreadY      = {PENCIL_SPREAD_MM:.3f} mm',
            f's:So/{src}/BeamPositionCutoffShape  = "Ellipse"',
            f'd:So/{src}/BeamPositionCutoffX      = {PENCIL_SPREAD_MM*2:.3f} mm',
            f'd:So/{src}/BeamPositionCutoffY      = {PENCIL_SPREAD_MM*2:.3f} mm',
        ]
    else:
        lines += [
            f's:So/{src}/BeamPositionDistribution = "None"',
        ]
    lines += [
        f's:So/{src}/BeamAngularDistribution   = "None"',
        f'i:So/{src}/NumberOfHistoriesInRun    = {nh}',
        ""
    ]

macro_text = "\n".join(lines)
out_path.write_text(macro_text, encoding="utf-8")

n_histories_sum = int(histories.sum())
n_beams, n_histories_sum, out_path.as_posix()


# Prepare plot data
x = positions[:, 0]
y = positions[:, 1]
r = PENCIL_SPREAD_MM if PENCIL_HAS_SPREAD else 0.5  # visualize radius even if 0

# Plot using seaborn for style
sns.set(style="whitegrid", context="talk")
plt.figure(figsize=(8, 8))
plt.scatter(x, y, s=20, color="royalblue", label="Pencil beam centers")

# Draw ellipse outline (beam cutoff)
theta = np.linspace(0, 2 * np.pi, 200)
plt.plot(RX_MM * np.cos(theta), RY_MM * np.sin(theta), "r--", label="Beam cutoff (ellipse)")

# Draw each pencil beam circle
for xi, yi in zip(x, y):
    circle = plt.Circle((xi, yi), r, color="blue", alpha=0.1)
    plt.gca().add_patch(circle)

plt.gca().set_aspect("equal", adjustable="box")
plt.xlabel("X position [mm]")
plt.ylabel("Y position [mm]")
plt.title("Pencil Beam Grid in XY Plane")
plt.legend()
plt.tight_layout()
plt.show()