/run/verbose 2

# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 45. 45.

# Specify zoom value:
/vis/viewer/zoom 65.

# Specify style (surface or wireframe):
/vis/viewer/set/style wireframe

# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 24 mm

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories rich
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)

# Draw hits at end of event:
/vis/scene/add/hits

# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma

# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true

# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue


/vis/ogl/set/displayListLimit 1000000000    
/vis/multithreading/maxEventQueueSize 0

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 100000
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#

/gun/particle gamma
/beam/momentum/momentumX 	0
/beam/momentum/momentumX/sigmaX	0.

/beam/momentum/momentumY 	0
/beam/momentum/momentumY/sigmaY	0.

/beam/momentum/momentumZ	1
/beam/momentum/momentumZ/sigmaZ	0.

/beam/energy/meanEnergy 30 keV
/beam/energy/sigmaEnergy  0.  keV

/tracking/verbose 0
/run/beamOn 10000

/vis/viewer/rebuild