###################################################
# Set of the verboses 
/control/verbose 0
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/process/verbose 0
/mpi/verbose 0

####################################################
# Randomiser
#/random/setDirectoryName .
#/random/setSavingFlag 1

####################################################
# physics list

#/process/em/fluo true #by default anyways
/process/em/auger true
#/process/em/pixe true

/run/setCutForAGivenParticle gamma 0.1 mm
/run/setCutForAGivenParticle e- 0.1 mm

####################################################

/mpi/showSeeds 

####################################################

# Initialisation procedure
/run/initialize

# GENERAL PARTICLE SOURCE
# general setup
/gps/verbose 0
/gps/particle gamma
/gps/pos/centre -0.5 -0.5 -61.5 mm
#/gps/pos/centre 0 0 0 mm
/gps/direction 0 0 1 # in z-direction
#/gps/ene/type Gauss
/gps/ene/mono 50.0 keV
#/gps/ene/sigma 20.0 keV


# Point source
/gps/pos/type Point
#/gps/ang/type iso

# Plane source
#/gps/pos/type Plane
#/gps/pos/shape Square
#/gps/pos/halfx 3. mm
#/gps/pos/halfy 3. mm

/mpi/beamOn 100000000
